mdapi/objects/CM_Backlog_Item__c.object
<CustomObject>
    <description>This CM object contains the individual backlog development takss which make up each sprint. and are assigned to a developer.  Note that this is the main object in the Change Management application.</description>
    <fields>
        <fullName>BackLog_ID__c</fullName>
        <description>Auto-Number field for Backlog ID Numbers.</description>
        <displayFormat>BL-{000}</displayFormat>
        <label>BackLog ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Component_Count__c</fullName>
        <label>Component Count</label>
        <summaryForeignKey>CM_Component__c.Backlog_Item__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Sprint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Which backlog items are assigned to each Sprint.  Not mandatory.</description>
        <label>Sprint</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CM_Sprint__c.Active__c</field>
                <operation>equals</operation>
                <value>true</value>
            </filterItems>
            <infoMessage>Please use an active sprint</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CM_Sprint__c</referenceTo>
        <relationshipLabel>Backlog Items</relationshipLabel>
        <relationshipName>Backlog_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>Approved by Business</fullName>
                </value>
                <value>
                    <fullName>Waiting On</fullName>
                </value>
                <value>
                    <fullName>Clarifying Req</fullName>
                </value>
                <value>
                    <fullName>Completed - Nothing to Deploy</fullName>
                </value>
                <value>
                    <fullName>Developer-Ready</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Ready for Feedback Demo</fullName>
                </value>
                <value>
                    <fullName>Ready to Demo</fullName>
                </value>
                <value>
                    <fullName>Ready for QA Deploy</fullName>
                </value>
                <value>
                    <fullName>Ready for QA</fullName>
                </value>
                <value>
                    <fullName>Passed QA / Ready for UAT Deploy</fullName>
                </value>
                <value>
                    <fullName>Ready for UAT</fullName>
                </value>
                <value>
                    <fullName>Passed UAT / Ready for Production Deploy</fullName>
                </value>
                <value>
                    <fullName>Deployed</fullName>
                </value>
                <value>
                    <fullName>Defer next sprint</fullName>
                </value>
                <value>
                    <fullName>Defer Later</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Backlog Item</label>
    <nameField>
        <label>Backlog Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/objects/CM_Sprint__c.object
<CustomObject>
    <description>CM (Change Management) Object used to define a Sprint or Release of new code to production.</description>
    <fields>
        <fullName>QA_Deploy_Date__c</fullName>
        <inlineHelpText>All new code should be deployed to the QA server by this date.</inlineHelpText>
        <label>QA Deploy Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QA_Signoff_Date__c</fullName>
        <description>The date all backlog items must be signed off</description>
        <inlineHelpText>The date all backlog items must be signed off</inlineHelpText>
        <label>QA Signoff Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the sprint, in general.  If some items are in development and some are in testing, be conservative and chose Development as the status.</description>
        <inlineHelpText>The status of the sprint, in general.  If some items are in development and some are in testing, be conservative and chose Development as the status.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning</fullName>
                    <default>true</default>
                    <label>Planning</label>
                </value>
                <value>
                    <fullName>Development</fullName>
                </value>
                <value>
                    <fullName>Quality Assurance Testing</fullName>
                </value>
                <value>
                    <fullName>User Acceptance Testing</fullName>
                </value>
                <value>
                    <fullName>Awaiting Deployment</fullName>
                </value>
                <value>
                    <fullName>Deployed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
                <value>
                    <fullName>Testing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UAT_Deploy_Date__c</fullName>
        <description>The date all backlog items must be deployed to UAT</description>
        <inlineHelpText>The date all backlog items must be deployed to UAT</inlineHelpText>
        <label>UAT Deploy Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>UAT_Signoff_Date__c</fullName>
        <description>The date all backlog items must be signed off in UAT</description>
        <inlineHelpText>The date all backlog items must be signed off in UAT</inlineHelpText>
        <label>UAT Signoff Date</label>
        <type>Date</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

mdapi/classes/BacklogItemTaskHelper.cls
/*
 * Backlog Item Task Helper
 * Create tasks when the status of backlog items changes
 * Change the status of a backlog item when tasks are completed
 */
// Only Global if certain methods are @future
//global class BacklogItemTaskHelper { 
public class BacklogItemTaskHelper {

	public static final String AUTOMATIC_TASK_TYPE = 'System Generated';
	
	// These are the backlog Items that will cause action to be taken
	public static final String READY_FOR_QA_DEPLOY_STATUS = 'Ready for QA Deploy';
	public static final String READY_FOR_QA_STATUS = 'Ready for QA';
	public static final String READY_FOR_UAT_DEPLOY_STATUS = 'Passed QA / Ready for UAT Deploy';
	public static final String READY_FOR_UAT_STATUS = 'Ready for UAT';
	public static final String READY_FOR_PROD_STATUS = 'Passed UAT / Ready for Production Deploy';
	public static Set<String> TASK_STATUS_SET = new Set<String> { READY_FOR_QA_DEPLOY_STATUS, READY_FOR_QA_STATUS, 
																  READY_FOR_UAT_DEPLOY_STATUS, READY_FOR_UAT_STATUS};
	
	// A Map with Leads and the User ID's in that role
	private static final String EM_LEAD_ROLE = 'Environment Management Lead';
	private static final String QA_LEAD_ROLE = 'Quality Assurance Lead';
	private static final String OPS_LEAD_ROLE = 'Business Operations Manager';
	private static Set<String> LEAD_ROLES = new Set<String> { EM_LEAD_ROLE, QA_LEAD_ROLE, OPS_LEAD_ROLE };
	private static Map<String, User> leadUserMap =  BacklogItemTaskHelper.loadLeadUserMap();
	
	// A Map with all of the sprints and their significant dates
	private static final Map<ID, CM_Sprint__c> sprintMap = new Map<ID, CM_Sprint__c>( [select id, name, QA_Deploy_Date__c, QA_Signoff_Date__c, UAT_Deploy_Date__c, UAT_Signoff_Date__c from CM_Sprint__c]);
	
	// Create tasks for backlog items
	//@future - Not doing these in the future for now.
	public static void createTasks( Set<ID> backlogItemIDs) {
		//System.debug( 'BacklogItemTaskHelper:createTasks with ' + backlogItemIDs.size() + ' Items.');
		
		List<Task> tasks = new List<Task>();
		
		// Loop through the backlog items creating tasks for each
		for ( CM_Backlog_Item__c bi : BacklogItemTaskHelper.getBacklogItems(backlogItemIDs)) {
			Task t = new Task();
			t.Subject = 'Agile Way Automated Task';
			t.Description = 'An Agile Way Backlog Item Status has changed to [' + bi.Status__c + ']';
			t.WhatId = bi.id;
			t.Type = BacklogItemTaskHelper.AUTOMATIC_TASK_TYPE;
			
			// Determine the due date of the task from the sprint (Note: Done separately because BI might not have a sprint)
			t.ActivityDate = BacklogItemTaskHelper.getTaskDueDate( bi.Sprint__c, bi.Status__c);
			
			// Key Here.  The backlog item's current status is put into the task so that when it is completed (the task), 
			// the trigger will fire and the backlog item's status will be pushed to the next value
			t.Current_Backlog_Item_Status__c = bi.Status__c;
			
			// Evaluate the task owner based on the status			
			if ( bi.Status__c == READY_FOR_QA_DEPLOY_STATUS ) {
				t.OwnerId = leadUserMap.get( EM_LEAD_ROLE).id;
				t.Subject += ' - Deploy Backlog Item Components to QA';
				t.Description += '\nDeploy Backlog Item to QA [' + bi.BackLog_ID__c + ' ' + bi.name + ']';
			} else if ( bi.Status__c == READY_FOR_QA_STATUS ) {
				t.OwnerId = leadUserMap.get( QA_LEAD_ROLE).id;
				t.Subject += ' - QA Backlog Item';
				t.Description += '\nQA Test Backlog Item [' + bi.BackLog_ID__c + ' ' + bi.name + ']';
			} else if ( bi.Status__c == READY_FOR_UAT_DEPLOY_STATUS) {
				t.OwnerId = leadUserMap.get( EM_LEAD_ROLE).id;
				t.Subject += ' - Deploy Backlog Item Components to UAT';
				t.Description += '\nDeploy Backlog Item to UAT [' + bi.BackLog_ID__c + ' ' + bi.name + ']';
			} else if ( bi.Status__c == READY_FOR_UAT_STATUS ) {
				t.OwnerId = leadUserMap.get( OPS_LEAD_ROLE).id;
				t.Subject += ' - UAT Backlog Item';
				t.Description += '\nUAT Test Backlog Item [' + bi.BackLog_ID__c + ' ' + bi.name + ']';
			} else {
				System.debug( 'BacklogItemTaskHelper:createTasks - Invalid Status on Backlog Item');
				t.OwnerId = UserInfo.getUserId(); // Assign to originator
			}
			
			tasks.add( t);
		}
		
		//System.debug( 'BacklogItemTaskHelper:createTasks - Tasks to created: ' + tasks.size());
		if ( tasks.size() > 0 ) {
			insert tasks;
		}

		// Try to create emails for these tasks
		try {
			// Now create the emails.  I don't think you can automatically generate the emails when the tasks are created.
			List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
			for ( Task t : tasks) {
				Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
				String[] toAddresses = new String[] { BacklogItemTaskHelper.getEmailByUserId( t.ownerId) };
				email.setToAddresses( toAddresses);
				email.setSubject( 'Agile Way Automated Task Notification');
				String body = '<b>Task Comments</b><br/> ' + t.Description.replace( '\n', '<br/>') + '<br/><br/>';
				body += '<b>Due Date:</b> ' + t.ActivityDate + '<br/><br/>';
				body += 'To view the task <a href=https://' + BacklogItemTaskHelper.getPod() + '.salesforce.com/' + t.id + '> Click Here</a>';
				body += '<br/><br/><b>Note:</b> By changing the status of this Task to ';
				body += '<i>Completed</i> the Backlog Item will be progressed to the next Status.';
				email.setHtmlBody( body);
				emails.add( email);
			}
			Messaging.sendEmail(emails);
		} catch ( Exception e) {
			System.debug( 'ERROR:::Exception occurred trying to send email for tasks.  ' + e.getMessage());
		}
	}

	// Pull Date from the sprint
	private static Date getTaskDueDate( ID sprintId, String biStatus ) {
		Date dueDate;
		try {
			if ( biStatus == READY_FOR_QA_DEPLOY_STATUS) {
				dueDate = BacklogItemTaskHelper.sprintMap.get( sprintId).QA_Deploy_Date__c;
			} else if ( biStatus == READY_FOR_QA_STATUS) {
				dueDate = BacklogItemTaskHelper.sprintMap.get( sprintId).QA_Signoff_Date__c;
			} else if ( biStatus == READY_FOR_UAT_DEPLOY_STATUS) {
				dueDate = BacklogItemTaskHelper.sprintMap.get( sprintId).UAT_Deploy_Date__c;
			} else if ( biStatus == READY_FOR_UAT_STATUS) {
				dueDate = BacklogItemTaskHelper.sprintMap.get( sprintId).UAT_Signoff_Date__c;
			} else {
				dueDate = null;
			}
		} catch ( Exception e) {
			System.debug( 'ERROR:::Exception occurred trying to get task due date: ' + e.getMessage());
		}
		return dueDate;
	}
	
	// Get Pod
	private static String getPod() {
		// This code is not portable between SFDC orgs.  It's tied to one specific production instance.
		if ( UserInfo.getOrganizationId() == '00DA0000000c3lf') {
			return 'login';
		} else {
			return 'test';
		}
	}
	
	// Get Email address by User Id
	private static String getEmailByUserId( ID userId ) {
		//System.debug( 'DEBUG:::Searching for Email address for user ID [' + userId + ']...');
		for ( User u : leadUserMap.values()) {
			if ( u.id == userId ) {
				//System.debug( 'DEBUG:::Found email address [' + u.Email + ']');
				return u.Email;
			}
		}
		
		return '';
	}

	// Update status for backlog items
	//@future - Not doing these in the future for now.
	public static void updateBacklogItemStatus( Set<ID> backlogItemIDs) {

		// Loop through the backlog items creating tasks for each
		List<CM_Backlog_Item__c> backlogItems = BacklogItemTaskHelper.getBacklogItems(backlogItemIDs);
		for ( CM_Backlog_Item__c bi : backlogItems) {
			String output = 'Backlog Item ' + bi.name + ' Changing Status from [' + bi.Status__c + ']';
			// Evaluate the next status based on the current status			
			if ( bi.Status__c == READY_FOR_QA_DEPLOY_STATUS) {
				bi.Status__c = READY_FOR_QA_STATUS;
			} else if ( bi.Status__c == READY_FOR_QA_STATUS ) {
				bi.Status__c = READY_FOR_UAT_DEPLOY_STATUS;
			} else if ( bi.Status__c == READY_FOR_UAT_DEPLOY_STATUS) {
				bi.Status__c = READY_FOR_UAT_STATUS;
			} else if ( bi.Status__c == READY_FOR_UAT_STATUS ) {
				bi.Status__c = READY_FOR_PROD_STATUS;
			} else {
				System.debug( 'BacklogItemTaskHelper:updateBacklogItemStatus - Untracked Status on Backlog Item');
			}
			output += ' to [' + bi.Status__c + ']';
			//System.debug( 'DEBUG:::' + output);
			
			update backlogItems;
			
		}		
	}

	// Generic method to get the Backlog Items via the IDs
	private static List<CM_Backlog_Item__c> getBacklogItems( Set<ID> backlogItemIDs) {
		return [select id, Name, BackLog_ID__c, Component_Count__c, Status__c, Sprint__c from CM_Backlog_Item__c where id in :backlogItemIDs];
	}
	
	// Get a map of the leads and the users
	private static Map<String, User> loadLeadUserMap() {
		Map<String, User> userMap = new Map<String, User>();
		for ( User u : [Select id, Username, Email, UserRole.Name From User where UserRole.Name in :LEAD_ROLES] ) {
			if ( !userMap.containsKey( u.UserRole.Name)) {
				userMap.put( u.UserRole.Name, u);
			}			
		}
		
		//System.debug( 'BacklogItemTaskHelper:loadLeadUserMap - Size of userMap is ' + userMap.size());
		return userMap;
	}
}